<?php

/**
 * BaseArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property int $seats
 * @property integer $sf_guard_user_id
 * @property integer $restaurant_id
 * @property Restaurant $Restaurant
 * @property sfGuardUser $sfGuardUser
 * @property DiningTable $Areas
 * 
 * @method string      getName()             Returns the current record's "name" value
 * @method int         getSeats()            Returns the current record's "seats" value
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method integer     getRestaurantId()     Returns the current record's "restaurant_id" value
 * @method Restaurant  getRestaurant()       Returns the current record's "Restaurant" value
 * @method sfGuardUser getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method DiningTable getAreas()            Returns the current record's "Areas" value
 * @method Area        setName()             Sets the current record's "name" value
 * @method Area        setSeats()            Sets the current record's "seats" value
 * @method Area        setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method Area        setRestaurantId()     Sets the current record's "restaurant_id" value
 * @method Area        setRestaurant()       Sets the current record's "Restaurant" value
 * @method Area        setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * @method Area        setAreas()            Sets the current record's "Areas" value
 * 
 * @package    yfoodnet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('area');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('seats', 'int', 4, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('restaurant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Restaurant', array(
             'local' => 'restaurant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DiningTable as Areas', array(
             'local' => 'id',
             'foreign' => 'area_id'));
    }
}