<?php

/**
 * BaseMenuOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $quantity
 * @property boolean $is_in_progress
 * @property boolean $is_ready
 * @property boolean $is_finished
 * @property boolean $using_paypal
 * @property integer $menu_id
 * @property integer $dining_table_id
 * @property Menu $Menu
 * @property DiningTable $DiningTable
 * 
 * @method int         getQuantity()        Returns the current record's "quantity" value
 * @method boolean     getIsInProgress()    Returns the current record's "is_in_progress" value
 * @method boolean     getIsReady()         Returns the current record's "is_ready" value
 * @method boolean     getIsFinished()      Returns the current record's "is_finished" value
 * @method boolean     getUsingPaypal()     Returns the current record's "using_paypal" value
 * @method integer     getMenuId()          Returns the current record's "menu_id" value
 * @method integer     getDiningTableId()   Returns the current record's "dining_table_id" value
 * @method Menu        getMenu()            Returns the current record's "Menu" value
 * @method DiningTable getDiningTable()     Returns the current record's "DiningTable" value
 * @method MenuOrder   setQuantity()        Sets the current record's "quantity" value
 * @method MenuOrder   setIsInProgress()    Sets the current record's "is_in_progress" value
 * @method MenuOrder   setIsReady()         Sets the current record's "is_ready" value
 * @method MenuOrder   setIsFinished()      Sets the current record's "is_finished" value
 * @method MenuOrder   setUsingPaypal()     Sets the current record's "using_paypal" value
 * @method MenuOrder   setMenuId()          Sets the current record's "menu_id" value
 * @method MenuOrder   setDiningTableId()   Sets the current record's "dining_table_id" value
 * @method MenuOrder   setMenu()            Sets the current record's "Menu" value
 * @method MenuOrder   setDiningTable()     Sets the current record's "DiningTable" value
 * 
 * @package    yfoodnet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenuOrder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu_order');
        $this->hasColumn('quantity', 'int', 4, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('is_in_progress', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_ready', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_finished', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('using_paypal', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('menu_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('dining_table_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Menu', array(
             'local' => 'menu_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DiningTable', array(
             'local' => 'dining_table_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}