<?php

/**
 * BaseDiningTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property string $name
 * @property integer $area_id
 * @property Area $Area
 * @property sfGuardUser $sfGuardUser
 * @property MenuOrder $MenuOrder
 * 
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method string      getName()             Returns the current record's "name" value
 * @method integer     getAreaId()           Returns the current record's "area_id" value
 * @method Area        getArea()             Returns the current record's "Area" value
 * @method sfGuardUser getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method MenuOrder   getMenuOrder()        Returns the current record's "MenuOrder" value
 * @method DiningTable setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method DiningTable setName()             Sets the current record's "name" value
 * @method DiningTable setAreaId()           Sets the current record's "area_id" value
 * @method DiningTable setArea()             Sets the current record's "Area" value
 * @method DiningTable setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * @method DiningTable setMenuOrder()        Sets the current record's "MenuOrder" value
 * 
 * @package    yfoodnet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDiningTable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dining_table');
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('area_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Area', array(
             'local' => 'area_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MenuOrder', array(
             'local' => 'id',
             'foreign' => 'dining_table_id'));
    }
}