<?php

/**
 * BaseRestaurant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $location
 * @property Area $Area
 * 
 * @method string     getName()     Returns the current record's "name" value
 * @method string     getLocation() Returns the current record's "location" value
 * @method Area       getArea()     Returns the current record's "Area" value
 * @method Restaurant setName()     Sets the current record's "name" value
 * @method Restaurant setLocation() Sets the current record's "location" value
 * @method Restaurant setArea()     Sets the current record's "Area" value
 * 
 * @package    yfoodnet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRestaurant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('restaurant');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Area', array(
             'local' => 'id',
             'foreign' => 'restaurant_id'));
    }
}