<?php

/**
 * DiningTableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiningTableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiningTableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiningTable');
    }
}