<?php

/**
 * MenuOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenuOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MenuOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MenuOrder');
    }
}