<?php

/**
 * PaypalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaypalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaypalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Paypal');
    }
}