<?php

/**
 * RestaurantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RestaurantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RestaurantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Restaurant');
    }
}